import { buildComponentContext, formatComponentContextPrompt } from './contextBuilder';
import { SYSTEM_TUTOR_PROMPT } from './prompts';
import { TutorRequest, TutorResponse, ChatHistoryMessage } from './types';

// OpenAI Provider Adapter
async function callOpenAI(
  systemPrompt: string,
  userQuery: string,
  history: ChatHistoryMessage[] = []
): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OpenAI API key missing');

  const messages = [
    { role: 'system', content: systemPrompt },
    ...history,
    { role: 'user', content: userQuery },
  ];

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: 'gpt-4o-mini',
      messages,
      temperature: 0.3,
    }),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`OpenAI API error ${res.status}: ${errText}`);
  }

  const data = await res.json();
  return data.choices[0]?.message?.content || 'No response generated by OpenAI.';
}

// Offline Synthesis Fallback Engine
function generateOfflineTutorCompletion(
  query: string,
  componentContextStr?: string
): string {
  const q = query.toLowerCase();

  if (componentContextStr) {
    if (q.includes('formula') || q.includes('equation') || q.includes('math') || q.includes('calculate')) {
      return `### Mathematical Formulation & Equations\n\nRefer to the governing equations in the active component context:\n\n${componentContextStr.slice(
        componentContextStr.indexOf('Governing Equations:'),
        componentContextStr.indexOf('Practical Applications:')
      )}\n\n**Engineering Tip:** When solving for values in real circuits, always ensure component wattage ($P = I^2 R$) and breakdown voltage limits ($V_{max}$) are not exceeded.`;
    }

    if (q.includes('pinout') || q.includes('pin') || q.includes('connect')) {
      return `### Pinout Configuration & Connection Guide\n\nCheck the pin mapping for the active component:\n\n${componentContextStr.slice(
        componentContextStr.indexOf('Key Properties & Specs:'),
        componentContextStr.indexOf('Governing Equations:')
      )}\n\nAlways double-check polarity markings and ground reference before applying power!`;
    }

    if (q.includes('application') || q.includes('use') || q.includes('where')) {
      return `### Practical Engineering Applications\n\n${componentContextStr.slice(
        componentContextStr.indexOf('Practical Applications:'),
        componentContextStr.indexOf('Limitations & Design Gotchas:')
      )}`;
    }
  }

  if (q.includes('resistor') || q.includes('ohm')) {
    return `### Resistors & Ohm's Law\n\n**Ohm's Law:** $V = I \\times R$\n- $V$: Voltage across resistor (Volts)\n- $I$: Current through resistor (Amperes)\n- $R$: Resistance value (Ohms $\\Omega$)\n\nResistors limit current and set voltage bias levels. Always verify thermal power dissipation ($P = I^2 \\times R$) against the component rating (typically 1/4W).`;
  }

  if (q.includes('mosfet') || q.includes('transistor')) {
    return `### Transistors & MOSFET Switching Mechanics\n\n- **BJT (Bipolar Junction Transistor):** Current-controlled device ($I_C = \\beta \\times I_B$).\n- **MOSFET (Field Effect Transistor):** Voltage-controlled device ($V_{gs}$). Requires near-zero steady-state gate current, offering high efficiency in switching power applications.`;
  }

  return `### electronicsAI Engineering Tutor\n\nI am your AI circuit design assistant. You can ask me questions about component physics, pinouts, governing equations, or practical circuit design. Select any component from the library to load its full context into our conversation!`;
}

// Central Tutor Orchestrator
export async function executeAITutor(request: TutorRequest): Promise<TutorResponse> {
  const { query, componentId, history = [] } = request;

  let fullSystemPrompt = SYSTEM_TUTOR_PROMPT;
  let componentName: string | undefined;
  let rawContextStr = '';

  if (componentId) {
    const contextData = buildComponentContext(componentId);
    if (contextData) {
      componentName = contextData.name;
      rawContextStr = formatComponentContextPrompt(contextData);
      fullSystemPrompt += `\n${rawContextStr}`;
    }
  }

  let reply = '';
  let providerUsed = 'Offline Engineering Synthesis Engine';

  // Check for external API keys
  if (process.env.OPENAI_API_KEY) {
    try {
      reply = await callOpenAI(fullSystemPrompt, query, history);
      providerUsed = 'OpenAI gpt-4o-mini';
    } catch (err) {
      console.warn('OpenAI call failed, utilizing offline fallback:', err);
      reply = generateOfflineTutorCompletion(query, rawContextStr);
      providerUsed = 'Offline Fallback Engine (OpenAI Fallback)';
    }
  } else {
    reply = generateOfflineTutorCompletion(query, rawContextStr);
  }

  return {
    reply,
    componentId,
    componentName,
    providerUsed,
    timestamp: new Date().toISOString(),
  };
}
